### ISSUE TITLE
snaphost download working only interactive

### ISSUE THREAD

**Issue by h00ked** [vpsfreecz/haveapi-webui#1]
There is problem with direct or with --from-snapshot command to download specified snapshot. Only work without any parameters in interactive choice.

$ vpsfreectl snapshot download -I 72
/Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:292:in `options': invalid option: -I (OptionParser::InvalidOption)
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:34:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:14:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:14:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/vpsfree-client-0.10.0/bin/vpsfreectl:4:in `<top (required)>'
	from /usr/local/bin/vpsfreectl:22:in `load'
	from /usr/local/bin/vpsfreectl:22:in `<main>'
$ vpsfreectl snapshot download --from-snapshot 72
/Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:292:in `options': invalid option: --from-snapshot (OptionParser::InvalidOption)
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:34:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:14:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:14:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/vpsfree-client-0.10.0/bin/vpsfreectl:4:in `<top (required)>'
	from /usr/local/bin/vpsfreectl:22:in `load'
	from /usr/local/bin/vpsfreectl:22:in `<main>'
$ vpsfreectl snapshot download 72
/Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/client/resource.rb:115:in `block (2 levels) in define_action': index failed: object Snapshot = 72 not found (HaveAPI::Client::ActionFailed)
	from /Library/Ruby/Gems/2.3.0/gems/vpsadmin-client-2.9.1/lib/vpsadmin/cli/commands/base_download.rb:11:in `find_or_create_dl'
	from /Library/Ruby/Gems/2.3.0/gems/vpsadmin-client-2.9.1/lib/vpsadmin/cli/commands/snapshot_download.rb:84:in `do_exec'
	from /Library/Ruby/Gems/2.3.0/gems/vpsadmin-client-2.9.1/lib/vpsadmin/cli/commands/snapshot_download.rb:69:in `exec'
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:78:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:14:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/haveapi-client-0.11.0/lib/haveapi/cli/cli.rb:14:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/vpsfree-client-0.10.0/bin/vpsfreectl:4:in `<top (required)>'
	from /usr/local/bin/vpsfreectl:22:in `load'
	from /usr/local/bin/vpsfreectl:22:in `<main>'

**Comment by aither64** [comment]
Solved on irc and it's actually for repo `vpsfree-client` or `vpsadmin-client`, but for the record:

```
vpsfreectl <command> [resource ids...] [-- [command options]]
vpsfreectl snapshot download <id> [-- [command options]]
vpsfreectl snapshot download 456 -- --from-snapshot 123
```
